const keyDataRu = [
  { text: 'ё', keycode: 192, shift: 'Ё' },
  { text: '2', keycode: 50, shift: '@' },
  { text: '3', keycode: 51, shift: '#' },
  { text: '4', keycode: 52, shift: '$' },
  { text: '5', keycode: 53, shift: '%' },
  { text: '6', keycode: 54, shift: '^' },
  { text: '7', keycode: 55, shift: '&' },
  { text: '8', keycode: 56, shift: '*' },
  { text: '9', keycode: 57, shift: '(' },
  { text: '0', keycode: 48, shift: ')' },
  { text: '-', keycode: 189, shift: '_' },
  { text: '=', keycode: 187, shift: '+' },
  { text: 'Backspace', keycode: 8 },
  { text: 'Tab', keycode: 9 },
  { text: 'й', keycode: 81, shift: 'Й' },
  { text: 'ц', keycode: 87, shift: 'Ц' },
  { text: 'у', keycode: 69, shift: 'У' },
  { text: 'к', keycode: 82, shift: 'К' },
  { text: 'е', keycode: 84, shift: 'Е' },
  { text: 'н', keycode: 89, shift: 'Н' },
  { text: 'г', keycode: 71, shift: 'Г' },
  { text: 'ш', keycode: 72, shift: 'Ш' },
  { text: 'щ', keycode: 74, shift: 'Щ' },
  { text: 'з', keycode: 90, shift: 'З' },
  { text: 'х', keycode: 88, shift: 'Х' },
  { text: 'ъ', keycode: 67, shift: 'Ъ' },
  { text: 'Del', keycode: 46 },
  { text: 'Caps Lock', keycode: 20 },
  { text: 'ф', keycode: 65, shift: 'Ф' },
  { text: 'ы', keycode: 83, shift: 'Ы' },
  { text: 'в', keycode: 68, shift: 'В' },
  { text: 'а', keycode: 70, shift: 'А' },
  { text: 'п', keycode: 80, shift: 'П' },
  { text: 'р', keycode: 82, shift: 'Р' },
  { text: 'о', keycode: 79, shift: 'О' },
  { text: 'л', keycode: 76, shift: 'Л' },
  { text: 'д', keycode: 68, shift: 'Д' },
  { text: 'ж', keycode: 59, shift: 'Ж' },
  { text: 'э', keycode: 222, shift: 'Э' },
  { text: 'Enter', keycode: 13 },
  { text: 'Shift', keycode: 16 },
  { text: 'я', keycode: 90, shift: 'Я' },
  { text: 'ч', keycode: 88, shift: 'Ч' },
  { text: 'с', keycode: 67, shift: 'С' },
  { text: 'м', keycode: 86, shift: 'М' },
  { text: 'и', keycode: 66, shift: 'И' },
  { text: 'т', keycode: 78, shift: 'Т' },
  { text: 'ь', keycode: 77, shift: 'Ь' },
  { text: 'б', keycode: 188, shift: 'Б' },
  { text: 'ю', keycode: 190, shift: 'Ю' },
  { text: '.', keycode: 191, shift: ',' },
  { text: 'arrowUp', keycode: 38 },
  { text: 'Shift', keycode: 16 },
  { text: 'сtrl', keycode: 17 },
  { text: 'win', keycode: 91 },
  { text: 'alt', keycode: 18 },
  { text: '', keycode: 32 },
  { text: 'alt', keycode: 18 },
  { text: 'сtrl', keycode: 17 },
  { text: 'arrowleft', keycode: 37 },
  { text: 'arrowBottom', keycode: 40 },
  { text: 'arrowRight', keycode: 39 },
];
export default keyDataRu;
